name: Linter Actions

on:
  push:
    branches: [ iac-811-gh-actions ] # leave push: blank to run jobs on all branches
  # pull_request:
  #   branches: [ main, staging ]

jobs:
  # Hadolint
  Hadolint:
    name: Hadolint
    strategy:
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Hadolint Action
        uses: jbergstroem/hadolint-gh-action@v1.11.0
        with:
          dockerfile: ./Dockerfile
          config_file: linting-configs/.hadolint.yaml
          error_level: 1 # Fail CI based on hadolint output (-1: never, 0: error, 1: warning, 2: info)

  # ShellCheck
  ShellCheck:
    name: ShellCheck
    strategy:
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run ShellCheck Action
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          ignore_names: additional_userdata.sh

  # TFLint
  TFLint:
    name: TFLint
    strategy:
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Cache Plugin Dir
      uses: actions/cache@v3
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v3.0.0
      with:
        tflint_version: latest

    - name: Show Version
      run: tflint --version

    - name: Initializing TFLint
      run: tflint --init --config linting-configs/.tflint.hcl

    - name: Run TFLint Action
      run: tflint

  # Terraform Formatting
  Terraform-Formatting:
    name: Auto Terraform Formatting
    strategy:
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Terraform-Fmt Action
        uses: dflook/terraform-fmt@v1.29.1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          commit-message: updated terraform formatting
          title: Reformated Terraform Files
          body: Updated terraform files to canonical format using `terraform fmt`.
          branch: automated-terraform-fmt
          delete-branch: false
          draft: true 

  # Checkov
  Checkov:
    name: Checkov
    strategy:
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Run Checkov Action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          config_file: linting-configs/.checkov.yaml
